'use client';
import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase';

type Field = { key:string; label:string; type?:'text'|'textarea'|'number'|'url'|'select'; required?:boolean; options?:string[]; placeholder?:string };
type Row = Record<string,any> & { id:string };
type Props = { table:string; title:string; description:string; fields:Field[]; searchKeys:string[]; defaults?:Record<string,any>; beforeSave?:(value:Record<string,any>)=>Record<string,any> };

export default function CmsCrud({table,title,description,fields,searchKeys,defaults={},beforeSave}:Props){
  const supabase=useMemo(()=>createClient(),[]); const [rows,setRows]=useState<Row[]>([]); const [editing,setEditing]=useState<Row|null>(null); const [form,setForm]=useState<Record<string,any>|null>(null); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  async function load(){setLoading(true);setError('');const {data,error}=await supabase.from(table).select('*').order('created_at',{ascending:false});if(error)setError(error.message);else setRows((data||[]) as Row[]);setLoading(false)}
  useEffect(()=>{load()},[]);
  const startNew=()=>{setEditing(null);setForm({...defaults});setError('')}; const startEdit=(row:Row)=>{setEditing(row);setForm({...row});setError('')}; const change=(key:string,value:any)=>setForm(v=>({...v,...(v||{}),[key]:value}));
  async function save(e:React.FormEvent){e.preventDefault();if(!form)return;setSaving(true);setError('');const payload=beforeSave?beforeSave({...form}):{...form};delete payload.id;delete payload.created_at;delete payload.updated_at;if(payload.status==='published'&&(table==='tutorin_tryouts'||table==='tutorin_articles')&&!payload.published_at)payload.published_at=new Date().toISOString();const result=editing?await supabase.from(table).update(payload).eq('id',editing.id):await supabase.from(table).insert(payload);if(result.error)setError(result.error.message);else{setEditing(null);setForm(null);await load()}setSaving(false)}
  async function remove(row:Row){if(!confirm(`Hapus “${row.title||row.name||row.slug||row.code||row.id}”?`))return;setError('');const {error}=await supabase.from(table).delete().eq('id',row.id);if(error)setError(error.message);else await load()}
  const filtered=rows.filter(row=>!query||searchKeys.some(k=>String(row[k]??'').toLowerCase().includes(query.toLowerCase())));
  return <><div className="section-title"><div className="eyebrow">CMS / {table.replace('tutorin_','')}</div><h1>{title}</h1><p>{description}</p></div>{error&&<div className="notice error-notice">{error}</div>}<div className="cms-toolbar"><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Cari ${title.toLowerCase()}…`}/><button className="button button-primary" onClick={startNew}>+ Tambah Baru</button></div>{form&&<form className="card cms-form" onSubmit={save}><div className="cms-form-head"><div><div className="eyebrow">{editing?'EDIT DATA':'DATA BARU'}</div><h3>{editing?'Ubah data':'Tambah data'}</h3></div><button type="button" className="button button-light" onClick={()=>{setEditing(null);setForm(null)}}>Tutup</button></div><div className="cms-form-grid">{fields.map(f=><label className="label" key={f.key}>{f.label}{f.type==='textarea'?<textarea className="input textarea" rows={5} value={form[f.key]??''} required={f.required} placeholder={f.placeholder} onChange={e=>change(f.key,e.target.value)}/>:f.type==='select'?<select className="input" value={form[f.key]??''} required={f.required} onChange={e=>change(f.key,e.target.value)}><option value="">Pilih…</option>{f.options?.map(o=><option key={o} value={o}>{o}</option>)}</select>:<input className="input" type={f.type||'text'} value={form[f.key]??''} required={f.required} placeholder={f.placeholder} onChange={e=>change(f.key,f.type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/>}</label>)}</div><div className="cms-actions"><button className="button button-primary" disabled={saving}>{saving?'Menyimpan…':editing?'Simpan Perubahan':'Simpan'}</button><button type="button" className="button button-light" onClick={()=>{setEditing(null);setForm(null)}}>Batal</button></div></form>}<div className="table-wrap"><table className="table"><thead><tr>{fields.slice(0,5).map(f=><th key={f.key}>{f.label}</th>)}<th>Status</th><th>Aksi</th></tr></thead><tbody>{loading?<tr><td colSpan={fields.length+2}>Memuat data…</td></tr>:filtered.map(row=><tr key={row.id}>{fields.slice(0,5).map(f=><td key={f.key}>{String(row[f.key]??'—').slice(0,90)}</td>)}<td><span className="badge">{row.status||'—'}</span></td><td><div className="row-actions"><button className="button button-light" onClick={()=>startEdit(row)}>Edit</button><button className="button button-danger" onClick={()=>remove(row)}>Hapus</button></div></td></tr>)}{!loading&&filtered.length===0&&<tr><td colSpan={fields.length+2}>Belum ada data.</td></tr>}</tbody></table></div></>;
}
